/*
ABS Data API (Beta)

Testing GetDataAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_GetDataAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GetDataAPIService GetData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dataflowIdentifier string
		var dataKey string

		resp, httpRes, err := apiClient.GetDataAPI.GetData(context.Background(), dataflowIdentifier, dataKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
