/*
ABS Data API (Beta)

Testing GetMetadataAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_GetMetadataAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GetMetadataAPIService GetLatestStructure", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var structureType string
		var agencyId string
		var structureId string

		resp, httpRes, err := apiClient.GetMetadataAPI.GetLatestStructure(context.Background(), structureType, agencyId, structureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GetMetadataAPIService GetStructures", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var structureType string
		var agencyId string
		var structureId string
		var structureVersion string

		resp, httpRes, err := apiClient.GetMetadataAPI.GetStructures(context.Background(), structureType, agencyId, structureId, structureVersion).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GetMetadataAPIService GetStructuresByAgencyId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var structureType string
		var agencyId string

		resp, httpRes, err := apiClient.GetMetadataAPI.GetStructuresByAgencyId(context.Background(), structureType, agencyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
